import Image from "next/image";
import React from "react";
export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};
const AboutPage = () => {
  return (
    <div className="max-w-7xl mx-auto px-3 ">
      {/* Main content grid */}
      <div className="grid  px-3 md:grid-cols-2 gap-8 items-center">
        {/* Left column: Text content */}
        <div className=" space-y-8">
          <h1 className="text-4xl sm:text-5xl text-neutralDGray font-semibold  ">
            About Agency
          </h1>
          <p className="text-base text-neutralGray md:w-3/4 mt-4">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Neque
            maxime illum iste repellat hic possimus impedit ut beatae fuga
            porro, recusandae quis dolorem odio veritatis modi, corporis ipsam
            vel suscipit.
          </p>
          <div className="flex gap-5 items-center justify-between">
            <div className=" flex flex-col gap-3">
              <h1 className=" text-blue-500">10 k</h1>
              <p className="text-sm">year of experience</p>
            </div>
            <div className=" flex flex-col gap-3">
              <h1 className=" text-blue-500">10 k</h1>
              <p className="text-sm">year of experience</p>
            </div>
            <div className=" flex flex-col gap-3">
              <h1 className=" text-blue-500">10 k</h1>
              <p className="text-sm ">year of experience</p>
            </div>
          </div>
        </div>
        {/* Right column: Image */}
        <div className=" w-full ">
          <Image
            src={"/banner.png"}
            alt="Tchamp Communications Banner"
            width={500}
            height={300}
          />
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
