import { TfiEmail } from "react-icons/tfi";
import { GiPhone } from "react-icons/gi";
export const metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};
const ContactPage = () => {
  return (
    
   
      <div className="max-w-7xl w-full mx-auto  grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Left column */}
        <div className="  p-6">
          <h1 className="text-2xl font-semibold mb-4">Contact Information</h1>
          <div className="flex items-center space-x-2 mb-2">
            <GiPhone />
            <p className="text-lg">Phone: 0745238509</p>
          </div>
          <div className="flex items-center space-x-2 mb-4">
            <TfiEmail />
            <p className="text-lg">Email: nyakundivictorn@gmail.com</p>
          </div>
        </div>

        {/* Right column */}
        <div className=" text-white  p-6">
          <form className="flex flex-col gap-5">
            <input
              className="border-none outline-none rounded-sm bg-slate-300 text-white px-4 py-2"
              type="text"
              placeholder="Name"
            />
            <input
              className="border-none outline-none rounded-sm bg-slate-300 text-white px-4 py-2"
              type="text"
              placeholder="Email"
            />
            <input
              className="border-none outline-none rounded-sm bg-slate-300 text-white px-4 py-2"
              type="tel"
              placeholder="Phone"
            />
            <textarea
              className="border-none outline-none rounded-sm bg-slate-300 text-white px-4 py-2"
              rows={5}
              placeholder="Message"
            ></textarea>
            <button
              className="bg-brandPrimary text-white py-3 rounded-sm hover:bg-brandPrimaryDark transition-colors duration-300"
              type="submit"
            >
              Send Message
            </button>
          </form>
        </div>
      </div>

  );
};

export default ContactPage;
