import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from 'react-hot-toast';
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: {
    default: " Next.js 14 Homepage",
    template:"%s | Next.js 14"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className=" min-h-[100vh] flex flex-col justify-between">
          <Navbar />  <Toaster position="top-right" />
          <div className="pt-5">

          {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
